### PR TITLE
Expanded/Corrected prerequisites for installation

### PR DESCRIPTION
**Pull request by ghost**
during my installation I discovered that while I had git installed (via github client) I couldn't use the pip install line because the PATH variable was not set.  I figured this warrented some kind of mention in the manual.  I'm not sure how PATH variables work on linux or if this is strictly a windows thing.

### CODE REVIEW

**Comment by CylonicRaider** [comment]
1. Consider reading the [Git commit style guide](http://chris.beams.io/posts/git-commit/).
2. Markdown (at least on GitHub) does not highlight [brackets] specially.
3. Does `pip` really require Git for a `git` URL? I shall verify.
4. Correct setting of `PATH` is definitely implied by “a working Python installation” (although one might mention that `pip` is not necessarily included).

On Linux, indeed, `PATH` is typically a fixed set of locations, and installation of programs puts the binaries in some of them, hence, a “normal” Python install should work from the command line out-of-the-box (as is expected). In contrast, on Windows, the command line has a much weaker culture, and — because of the lack of centralized package management — software is kept in individual directories without amending `PATH`, leaving that up to the user. In the case of Python, though, the [installation guide](https://docs.python.org/3/using/windows.html#installing-python) is quite comprehensive, and the installer seems to allow doing that on the very first page (for recent versions).

**Comment by CylonicRaider** [comment]
Sorry, `pip` seems to depend on an external Git indeed.

P.S. In general, the installation guide — as the remainder of the library — is rather aimed at technically oriented users anyway, which is why I list Python as a “silent presumption”.

**Comment by CylonicRaider** [comment]
I've proposed an alternate... expression [pmfisher80/master](https://github.com/CylonicRaider/basebot/tree/pmfisher80/master).

P.S. Sorry for mis-spelling your name.

**Comment by ghost** [comment]
Re: mispelling, I didn't even notice heh, you anglicized it, heh

**Pull request merged**
